spring:
  datasource:
    url: jdbc:mariadb://localhost:13306/tory
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
---
mybatis:
  mapper-locations: classpath:/mapper/*.xml
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher